#[theme]
#base = "light"  # Explicit light mode activation
#primaryColor = "#FF6B6B"       # Energetic coral (pop)
#accentColor = "#FFD93D"        # Sunny yellow (attention)
#backgroundColor = "#FFFFFF"    # Crisp white
#secondaryBackgroundColor = "#F8F9FA"  # Airy light gray
#textColor = "#2B2D42"          # Professional navy
#font = "sans serif" # Optional for brand consistency

[theme]
base = "dark"  # ← Crucial dark mode activation
primaryColor = "#2A9D8F"     # Maintains brand consistency
accentColor = "#E76F51"      # Warm contrast for CTAs
backgroundColor = "#121212"  # True dark (not pure black)
secondaryBackgroundColor = "#1E1E1E"  # Rich dark gray
textColor = "#E0E0E0"        # Soft white for readability
font = "sans serif"          # Streamlit-safe font declaration
